# Generated by Django 5.2 on 2026-02-05 15:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cascore',
            options={'ordering': ['-created_at'], 'verbose_name': 'CA Score (CA1 + CA2)', 'verbose_name_plural': 'CA Scores'},
        ),
        migrations.RemoveField(
            model_name='cascore',
            name='ca_score',
        ),
        migrations.RemoveField(
            model_name='cascore',
            name='max_theory_score',
        ),
        migrations.RemoveField(
            model_name='cascore',
            name='theory_score',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='ca_score',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='exam_score',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='total_exam_questions',
        ),
        migrations.AddField(
            model_name='cascore',
            name='ca1_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='First Continuous Assessment score (max 15)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='cascore',
            name='ca2_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Second Continuous Assessment score (max 15)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='examresult',
            name='ca1_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='First Continuous Assessment (max 15)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='examresult',
            name='ca2_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Second Continuous Assessment (max 15)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='examresult',
            name='cumulative_grade',
            field=models.CharField(blank=True, help_text='Grade based on cumulative score', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='cumulative_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cumulative average across terms', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='first_term_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='First term total (for cumulative calculation)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='obj_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Objective/CBT score (max 30) - RAW score from CBT', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='examresult',
            name='remark',
            field=models.CharField(default='Fail', help_text='Grade remark (Excellent, Very Good, Good, Pass, Fair, Fail)', max_length=20),
        ),
        migrations.AddField(
            model_name='examresult',
            name='second_term_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Second term total (for cumulative calculation)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='third_term_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Third term total (for cumulative calculation)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='total_obj_questions',
            field=models.IntegerField(default=30, help_text='Total MCQ questions in the CBT exam'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='grade',
            field=models.CharField(db_index=True, default='F', help_text='Grade based on Nigerian grading scale', max_length=2),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='position',
            field=models.IntegerField(blank=True, help_text='Position in class for this subject', null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='CBT submission timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='theory_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Theory/Essay score (max 40)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='CA1 + CA2 + OBJ + Theory (max 100)', max_digits=5),
        ),
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_mark_percentage', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum cumulative score to pass (default 50%)', max_digits=5)),
                ('compulsory_subject_ids', models.JSONField(default=list, help_text='List of subject IDs that must be passed (e.g., Math, English)')),
                ('minimum_additional_subjects', models.IntegerField(default=5, help_text='Minimum number of other subjects to pass (default 5)')),
                ('promotion_mode', models.CharField(choices=[('auto', 'Automatic (system decides)'), ('recommend', 'Recommend (admin approves)'), ('manual', 'Manual (admin decides)')], default='recommend', max_length=20)),
                ('allow_carryover', models.BooleanField(default=False, help_text='Allow students to be promoted with failed subjects')),
                ('max_carryover_subjects', models.IntegerField(default=2, help_text='Maximum failed subjects allowed for carryover')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(blank=True, help_text='Leave blank to apply to all classes', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.classlevel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='users.academicsession')),
            ],
            options={
                'verbose_name': 'Promotion Rule',
                'verbose_name_plural': 'Promotion Rules',
                'unique_together': {('session', 'class_level')},
            },
        ),
    ]
