# Generated by Django 5.0 on 2025-10-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='class_level',
            field=models.CharField(choices=[('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SS1', 'SS1'), ('SS2', 'SS2'), ('SS3', 'SS3')], help_text='e.g., SS1, JSS2', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(help_text='e.g., +2348012345678', max_length=15),
        ),
    ]
