# Generated by Django 5.0 on 2025-10-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(choices=[('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SS1 Science', 'SS1 Science'), ('SS1 Commercial', 'SS1 Commercial'), ('SS1 Art', 'SS1 Art'), ('SS2 Science', 'SS2 Science'), ('SS2 Commercial', 'SS2 Commercial'), ('SS2 Art', 'SS2 Art'), ('SS3 Science', 'SS3 Science'), ('SS3 Commercial', 'SS3 Commercial'), ('SS3 Art', 'SS3 Art')], help_text='e.g., SS2 Science', max_length=20),
        ),
        migrations.AddIndex(
            model_name='classcounter',
            index=models.Index(fields=['class_name'], name='users_class_class_n_3547c0_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_number'], name='users_stude_admissi_a83840_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['class_name', 'is_active'], name='users_stude_class_n_54b025_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role', 'is_active'], name='users_userp_role_2f1295_idx'),
        ),
    ]
