# Generated by Django 5.0 on 2025-10-08 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_student_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SS1 Science', 'SS1 - Science'), ('SS1 Commercial', 'SS1 - Commercial'), ('SS1 Art', 'SS1 - Art'), ('SS2 Science', 'SS2 - Science'), ('SS2 Commercial', 'SS2 - Commercial'), ('SS2 Art', 'SS2 - Art'), ('SS3 Science', 'SS3 - Science'), ('SS3 Commercial', 'SS3 - Commercial'), ('SS3 Art', 'SS3 - Art')], max_length=50)),
                ('session_year', models.CharField(default='2025/2026', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Assignment',
                'verbose_name_plural': 'Teacher Assignments',
                'unique_together': {('teacher', 'class_name')},
            },
        ),
    ]
