# Generated by Django 5.2 on 2026-02-08 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_cascore_options_remove_cascore_ca_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cascore",
            name="ca1_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="First Continuous Assessment score (flexible marks)",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="cascore",
            name="ca2_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Second Continuous Assessment score (flexible marks)",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="ca1_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="First Continuous Assessment (flexible marks)",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="ca2_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Second Continuous Assessment (flexible marks)",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="obj_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Objective/CBT RAW score (equals correct answers, no scaling)",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="theory_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Theory/Essay score (flexible marks)",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="total_obj_questions",
            field=models.IntegerField(
                default=0, help_text="Total MCQ questions in the CBT exam"
            ),
        ),
    ]
