# Generated by Django 5.0 on 2025-10-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_student_class_name_alter_student_class_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.CharField(blank=True, choices=[('Science', 'Science'), ('Commercial', 'Commercial'), ('Art', 'Art'), ('General', 'General')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(help_text='e.g., +23480...', max_length=15),
        ),
    ]
