# Generated by Django 5.0 on 2025-09-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('staffs', 'Staffs'), ('teacher', 'Teacher')], default='staff', max_length=10),
        ),
    ]
