# Generated by Django 5.2 on 2026-02-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_promotionrule_category_pass_marks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promotionrule",
            name="category_pass_marks",
        ),
    ]
