# Generated by Django 5.2.3 on 2025-11-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_student_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='users_student',
        ),
    ]
