# Generated by Django 5.2 on 2025-12-30 17:20

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_student_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Session',
                'verbose_name_plural': 'Academic Sessions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('JSS1', 'Junior Secondary 1'), ('JSS2', 'Junior Secondary 2'), ('JSS3', 'Junior Secondary 3'), ('SS1', 'Senior Secondary 1'), ('SS2', 'Senior Secondary 2'), ('SS3', 'Senior Secondary 3')], max_length=10, unique=True)),
                ('order', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Class Level',
                'verbose_name_plural': 'Class Levels',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_levels', models.ManyToManyField(related_name='subjects', to='users.classlevel')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActiveStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150)),
                ('password_plain', models.CharField(max_length=50)),
                ('password_hash', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('state_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('local_govt_area', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=200, null=True)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('passport', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_enrolled', to=settings.AUTH_USER_MODEL)),
                ('enrollment_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolled_students', to='users.academicsession')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_students', to='users.classlevel')),
                ('subjects', models.ManyToManyField(blank=True, related_name='students', to='users.subject')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['admission_number'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='users.academicsession')),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'ordering': ['session', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_score', models.IntegerField()),
                ('exam_score', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('grade', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Fair'), ('F', 'F - Fail')], max_length=1)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('class_average', models.FloatField(blank=True, null=True)),
                ('total_students', models.IntegerField(blank=True, null=True)),
                ('highest_score', models.IntegerField(blank=True, null=True)),
                ('lowest_score', models.IntegerField(blank=True, null=True)),
                ('answers_json', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='users.activestudent')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_results', to='users.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.term')),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exam Results',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CAScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('max_score', models.IntegerField(default=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_scores', to='users.activestudent')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.term')),
            ],
            options={
                'verbose_name': 'CA Score',
                'verbose_name_plural': 'CA Scores',
            },
        ),
        migrations.AddIndex(
            model_name='activestudent',
            index=models.Index(fields=['admission_number'], name='users_activ_admissi_952754_idx'),
        ),
        migrations.AddIndex(
            model_name='activestudent',
            index=models.Index(fields=['class_level'], name='users_activ_class_l_1e577b_idx'),
        ),
        migrations.AddIndex(
            model_name='activestudent',
            index=models.Index(fields=['is_active'], name='users_activ_is_acti_276fd7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('session', 'name')},
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student', 'session', 'term'], name='users_examr_student_2166c4_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['subject', 'session', 'term'], name='users_examr_subject_2c8b77_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('student', 'subject', 'session', 'term')},
        ),
        migrations.AddIndex(
            model_name='cascore',
            index=models.Index(fields=['student', 'session', 'term'], name='users_casco_student_476f45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cascore',
            unique_together={('student', 'subject', 'session', 'term')},
        ),
    ]
