# Generated by Django 5.2 on 2026-01-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_academicsession_classlevel_subject_activestudent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activestudent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
