# Generated by Django 5.2.3 on 2025-11-06 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='image_count',
            new_name='media_count',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='image_urls',
            new_name='media_urls',
        ),
    ]
