# Generated by Django 5.2.3 on 2025-11-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_rename_image_count_gallery_media_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
