# Generated by Django 5.2 on 2026-01-24 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_galleryimage_alter_gallery_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gallery',
            name='gallery_gal_is_acti_51dcda_idx',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['is_active', '-created_at'], name='gallery_active_list_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['created_by', 'is_active'], name='gallery_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['is_active', 'title'], name='gallery_search_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['gallery', 'is_active'], name='galleryimg_gallery_active_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['gallery', 'order'], name='galleryimg_gallery_order_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['gallery', 'is_active', 'order'], name='galleryimg_list_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['-created_at'], name='gallery_gal_created_947a7f_idx'),
        ),
    ]
