# Generated by Django 5.2.3 on 2025-10-16 08:07

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('media', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('published', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Item',
                'verbose_name_plural': 'Content Items',
                'ordering': ['-publish_date'],
                'indexes': [models.Index(fields=['slug'], name='content_con_slug_36a701_idx'), models.Index(fields=['published', 'is_active'], name='content_con_publish_743ce1_idx')],
            },
        ),
    ]
