# Generated by Django 5.2.3 on 2025-11-20 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('news', 'News Article')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['content_type'], name='content_con_content_8fbc99_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['-publish_date'], name='content_con_publish_0bad07_idx'),
        ),
    ]
