# Generated by Django 5.2 on 2026-01-24 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_contentitem_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contentitem',
            name='content_con_publish_743ce1_idx',
        ),
        migrations.RemoveIndex(
            model_name='contentitem',
            name='content_con_content_8fbc99_idx',
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['is_active', 'published'], name='content_active_published_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['is_active', 'content_type'], name='content_active_type_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['is_active', 'published', '-publish_date'], name='content_public_list_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['content_type', 'is_active', '-publish_date'], name='content_type_list_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['created_by', 'is_active'], name='content_creator_idx'),
        ),
    ]
