# Generated by Django 5.0 on 2025-10-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=10)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('stream', models.CharField(blank=True, choices=[('Science', 'Science'), ('Commercial', 'Commercial'), ('Art', 'Art'), ('General', 'General')], max_length=15, null=True)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('session_year', models.CharField(default='2025/2026', max_length=9)),
            ],
            options={
                'verbose_name': 'Teacher Assignment',
                'verbose_name_plural': 'Teacher Assignments',
            },
        ),
    ]
