# Generated by Django 5.0 on 2025-10-06 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('users', '0002_alter_student_class_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'date'], name='attendance__student_588cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['class_obj', 'date'], name='attendance__class_o_ad0734_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['teacher', 'name'], name='attendance__teacher_581cdf_idx'),
        ),
    ]
