# Generated by Django 5.0 on 2025-10-08 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancerecord_date_and_more'),
        ('users', '0003_teacherassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveIndex(
            model_name='attendancerecord',
            name='attendance__student_588cfe_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancerecord',
            name='attendance__class_o_ad0734_idx',
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'date')},
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.student'),
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='class_obj',
        ),
    ]
